// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using digitalmaktabapi.Data;

#nullable disable

namespace digitalmaktabapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240728221833_MakeSchoolLogoOptional")]
    partial class MakeSchoolLogoOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("digitalmaktabapi.Models.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreationUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("digitalmaktabapi.Models.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreationUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("digitalmaktabapi.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryPhoneCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreationUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("digitalmaktabapi.Models.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreationUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("District");
                });

            modelBuilder.Entity("digitalmaktabapi.Models.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreationUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("School");
                });

            modelBuilder.Entity("digitalmaktabapi.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AsasNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BloodGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrotherName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClassType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreationUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurrentBranchId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentClass")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisabilityType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FCousinName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FUncleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FatherNameEnglish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FatherNameNative")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstNameEnglish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstNameNative")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GrandFatherNameEnglish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrandFatherNameNative")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IsOrphan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JoiningAge")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JoiningBranchId")
                        .HasColumnType("TEXT");

                    b.Property<int>("JoiningClass")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("JoiningYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastNameEnglish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastNameNative")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MCousinName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MUncleName")
                        .HasColumnType("TEXT");

                    b.Property<int>("MotherTongue")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Shift")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(4);

                    b.HasKey("Id");

                    b.HasIndex("CurrentBranchId");

                    b.HasIndex("JoiningBranchId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("digitalmaktabapi.Models.City", b =>
                {
                    b.HasOne("digitalmaktabapi.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("digitalmaktabapi.Models.District", b =>
                {
                    b.HasOne("digitalmaktabapi.Models.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("digitalmaktabapi.Models.School", b =>
                {
                    b.OwnsOne("digitalmaktabapi.Models.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("SchoolId")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("AddressType")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid?>("DistrictId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Region")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Village")
                                .HasColumnType("TEXT");

                            b1.HasKey("SchoolId");

                            b1.HasIndex("DistrictId");

                            b1.ToTable("School");

                            b1.HasOne("digitalmaktabapi.Models.District", "District")
                                .WithMany()
                                .HasForeignKey("DistrictId");

                            b1.WithOwner()
                                .HasForeignKey("SchoolId");

                            b1.Navigation("District");
                        });

                    b.OwnsOne("digitalmaktabapi.Models.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("SchoolId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("CountryId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("SchoolId");

                            b1.HasIndex("CountryId");

                            b1.ToTable("School");

                            b1.HasOne("digitalmaktabapi.Models.Country", "Country")
                                .WithMany()
                                .HasForeignKey("CountryId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("SchoolId");

                            b1.Navigation("Country");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("digitalmaktabapi.Models.Student", b =>
                {
                    b.HasOne("digitalmaktabapi.Models.Branch", "CurrentBranch")
                        .WithMany()
                        .HasForeignKey("CurrentBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("digitalmaktabapi.Models.Branch", "JoiningBranch")
                        .WithMany()
                        .HasForeignKey("JoiningBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("digitalmaktabapi.Models.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("digitalmaktabapi.Models.NationalId", "NationalId", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ElectoricNationIdNumber")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("NationalIdNumber")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Page")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("RegisterNumber")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Volume")
                                .HasColumnType("INTEGER");

                            b1.HasKey("StudentId");

                            b1.ToTable("Students");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.OwnsOne("digitalmaktabapi.Models.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("CountryId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("StudentId");

                            b1.HasIndex("CountryId");

                            b1.ToTable("Students");

                            b1.HasOne("digitalmaktabapi.Models.Country", "Country")
                                .WithMany()
                                .HasForeignKey("CountryId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("StudentId");

                            b1.Navigation("Country");
                        });

                    b.OwnsOne("digitalmaktabapi.Models.Address", "PrimaryAddress", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("AddressType")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid?>("DistrictId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Region")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Village")
                                .HasColumnType("TEXT");

                            b1.HasKey("StudentId");

                            b1.HasIndex("DistrictId");

                            b1.ToTable("Students");

                            b1.HasOne("digitalmaktabapi.Models.District", "District")
                                .WithMany()
                                .HasForeignKey("DistrictId");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");

                            b1.Navigation("District");
                        });

                    b.OwnsOne("digitalmaktabapi.Models.Address", "SecondaryAddress", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("AddressType")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid?>("DistrictId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Region")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Village")
                                .HasColumnType("TEXT");

                            b1.HasKey("StudentId");

                            b1.HasIndex("DistrictId");

                            b1.ToTable("Students");

                            b1.HasOne("digitalmaktabapi.Models.District", "District")
                                .WithMany()
                                .HasForeignKey("DistrictId");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");

                            b1.Navigation("District");
                        });

                    b.Navigation("CurrentBranch");

                    b.Navigation("JoiningBranch");

                    b.Navigation("NationalId");

                    b.Navigation("PhoneNumber");

                    b.Navigation("PrimaryAddress")
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("SecondaryAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("digitalmaktabapi.Models.City", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("digitalmaktabapi.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("digitalmaktabapi.Models.School", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
